# Generated by Django 4.1.1 on 2023-01-25 08:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('AreaId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('AreaName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'Area',
            },
        ),
        migrations.CreateModel(
            name='BlogCategory',
            fields=[
                ('BlogId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('BlogType', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'BlogCategory',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('CatId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CatName', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'Category',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('CityId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('CityName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'City',
            },
        ),
        migrations.CreateModel(
            name='HealthCondition',
            fields=[
                ('HcId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('HcName', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'HealthCondition',
            },
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('OrderStatusId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Status', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'OrderStatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('PaymentStatusId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PaymentStatus', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'PaymentStatus',
            },
        ),
        migrations.CreateModel(
            name='PaymentType',
            fields=[
                ('PaymentTypeId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PaymentType', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'PaymentType',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('RoleId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('RoleName', models.CharField(max_length=15)),
            ],
            options={
                'db_table': 'Role',
            },
        ),
        migrations.CreateModel(
            name='State',
            fields=[
                ('StateId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('StateName', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'State',
            },
        ),
        migrations.CreateModel(
            name='SubCategory',
            fields=[
                ('SubCatId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SubCatName', models.CharField(max_length=10)),
                ('CatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.category')),
            ],
            options={
                'db_table': 'SubCategory',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('UserId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=25)),
                ('FirstName', models.CharField(max_length=15)),
                ('LastName', models.CharField(max_length=15)),
                ('Password', models.CharField(max_length=25)),
                ('Mobile', models.IntegerField(default='', max_length=10)),
                ('Email', models.EmailField(max_length=25)),
                ('Address', models.CharField(max_length=60)),
                ('otp', models.IntegerField()),
                ('otp_used', models.IntegerField()),
                ('AreaId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.area')),
                ('CityId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.city')),
                ('RoleId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.role')),
                ('StateId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.state')),
            ],
            options={
                'db_table': 'User',
            },
        ),
        migrations.CreateModel(
            name='SubSubCategory',
            fields=[
                ('SubSubCatId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('SubSubCatName', models.CharField(max_length=10)),
                ('SubCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.subcategory')),
            ],
            options={
                'db_table': 'SubSubCategory',
            },
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('StoreId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('StoreName', models.CharField(max_length=30)),
                ('Address', models.CharField(max_length=50)),
                ('OwnerName', models.CharField(max_length=30)),
                ('OwnerEmail', models.EmailField(max_length=30)),
                ('LicenseNumnber', models.IntegerField(default='', max_length=20)),
                ('Mobile', models.IntegerField(default='', max_length=10)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.user')),
            ],
            options={
                'db_table': 'Store',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('ProductId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('ProductName', models.CharField(max_length=25)),
                ('ProductPrice', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ProductQty', models.IntegerField(default='', max_length=5)),
                ('ProductImage', models.ImageField(default='', upload_to='shop/images')),
                ('HCId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.healthcondition')),
                ('StoreId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.store')),
                ('SubCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.subcategory')),
                ('SubSubCatId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.subsubcategory')),
            ],
            options={
                'db_table': 'Product',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('PaymentId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('PaymentAmunt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('PaymentDate', models.DateTimeField()),
                ('PaymentStatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.paymentstatus')),
                ('PaymentTypeId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.paymenttype')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.user')),
            ],
            options={
                'db_table': 'Payment',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('OrderDate', models.DateTimeField()),
                ('OrderStatusId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.orderstatus')),
                ('PaymentID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.payment')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.product')),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.user')),
            ],
            options={
                'db_table': 'Order',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('BatchId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('Company', models.CharField(max_length=15)),
                ('Name', models.CharField(max_length=20)),
                ('MFG', models.DateField()),
                ('EXPDate', models.DateField()),
                ('Qty', models.IntegerField(default='', max_length=10)),
                ('HCId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.healthcondition')),
                ('ProductId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.product')),
            ],
            options={
                'db_table': 'Medicine',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('FeedBackId', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('FeedBackDate', models.DateField()),
                ('FeedBackDesc', models.CharField(max_length=250)),
                ('UserId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.user')),
            ],
            options={
                'db_table': 'FeedBack',
            },
        ),
        migrations.AddField(
            model_name='city',
            name='StateId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.state'),
        ),
        migrations.AddField(
            model_name='area',
            name='CityId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='MedicsApp.city'),
        ),
    ]
